#!/bin/bash
PATH-$PATH:/action
clear
'c
"c
c
\c
#!/bin/bash                                                                                                                     
PATH-$PATH:/action
'c
root@8992cb9fc3ed:~/alx-system_engineering-devops#
c
root@8992cb9fc3ed:~/alx-system_engineering-devops#ls
root@8992cb9fc3ed:~/alx-system_engineering-devops# ls
cd root
'C
CLEAR
clrear
